### ISSUE TITLE
ISSUE_TEMPLATE 생성

### ISSUE THREAD

**Issue by R3gardless** [R3gardless/r3gardless.dev#4]
## ✅ 목표
.github/ISSUE_TEMPLATE/feature_implement.yml 생성

---

## 📦 작업 범위

- [x] .github/ISSUE_TEMPLATE/feature_implement.yml 생성

---

### `feature_implement.yml`

```yaml
name: Feature Implementation
description: 새로운 기능 또는 작업을 구현하기 위한 이슈 템플릿입니다.
title: "feat: {기능명}"
labels: ["feature", "enhancement"]
assignees: ['R3gardless']
body:
  - type: textarea
    id: goal
    attributes:
      label: ✅ 목표 (Why)
      description: |
        이슈를 통해 **최종적으로 달성하려는 목표**를 작성해주세요.
        예: 사용자 경험 개선, 코드 일관성 확보, 성능 최적화 등 상위-level 목표
      placeholder: '예: TailwindCSS 글로벌 스타일 초기화로 전체 UI 스타일 일관성 확보'
    validations:
      required: true
```
